name: Deploy to Production

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Tailscale
              run: |
                  sudo curl -fsSL https://tailscale.com/install.sh | sh

            - name: Authenticate with Tailscale
              env:
                  TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
              run: |
                  sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY

            - name: Deploy via Tailscale SSH
              env:
                  SERVER_IP: ${{ secrets.SERVER_TAILSCALE_IP }}
              run: |
                  sudo tailscale ssh git@$SERVER_IP << 'EOF'
                  sudo curl https://raw.githubusercontent.com/Server-Departementet/Riksdagen/refs/heads/main/deploy-code/deploy-update.sh -o riksdagen-deploy-update.sh
                  sudo bash riksdagen-deploy-update.sh branch origin/main
                  sudo rm riksdagen-deploy-update.sh
                  EOF
